nodeLinker: node-modules

npmRegistryServer: "http://nexus.medlinker.com/repository/group-npm/"

npmPublishAccess: "public"

npmPublishRegistry: "https://nexus.medlinker.com/repository/local-npm/"

unsafeHttpWhitelist:
  - "nexus.medlinker.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
