nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

npmPublishAccess: 'public'

npmPublishRegistry: 'https://registry.npmjs.org/'

unsafeHttpWhitelist:
  - 'nexus.medlinker.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.2.1.cjs
